### ISSUE TITLE
Prodcution build run

### ISSUE THREAD

**Issue by Hashpot** [glv/snergly#1]

**Comment by glv** [comment]
Hi … sorry to take a while to respond. You closed the issue; does that mean you got it working?

I built this in 2016 as a Clojure "practice project" because I was talking to a couple companies about Clojure jobs and hadn't written Clojure seriously since 2010. I ended up getting a position where we did not use Clojure, and I didn't have much time for fun side projects, so I haven't paid attention to this since. ClojureScript tooling was going through a lot of changes around 2016, so I'm sure a lot of the setup for this is quite outdated.

However, I'm now working for a company that does a lot of Clojure, and I'll have some time to look at this again. I'll start by updating tooling and dependencies; I'm not sure what form that will take, but I'm pretty sure one of the first things I'll do will be to convert the UI framework from Om Next to Fulcro.
